server:
  port: 8088

spring:
  application:
    name: spring-boot-shipping-service
  cloud:
    stream:
      bindings:
        input:
          destination: customer
          consumer:
            useNativeDecoding: true
        order:
          destination: order
          consumer:
            useNativeDecoding: true
        output:
          destination: order
          producer:
            useNativeEncoding: true
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              schema:
                registry:
                  url: http://localhost:8081
              value:
                subject:
                  name:
                    strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
          bindings:
            order:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
