spring:
  application:
    name: spring-boot-customer-service
  cloud:
    stream:
      kafka:
        bindings:
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.IntegerSerializer
                value:
                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema:
                  registry:
                    url: http://localhost:8081
      bindings:
        output:
          destination: customer
          producer:
            useNativeEncoding: true
