spring:
  application:
    name: spring-boot-customer-service-v2
  cloud:
    stream:
      kafka:
        bindings:
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.IntegerSerializer
                value:
                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  subject:
                    name:
                      strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
                schema:
                  registry:
                    url: http://localhost:8081

      bindings:
        output:
          destination: customer
          producer:
            useNativeEncoding: true

server:
  port: 8086
